
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int COMILLADOBLE = 38;
  public static final int MASMAS = 23;
  public static final int DOSPUNTOS = 12;
  public static final int SCANF = 29;
  public static final int MENOSMENOS = 25;
  public static final int CHAR = 9;
  public static final int PUNTOYCOMA = 11;
  public static final int DIFERENTE = 27;
  public static final int NUMEROS = 3;
  public static final int INTEGER = 8;
  public static final int LLAVEDER = 17;
  public static final int ASTERISCO = 10;
  public static final int FOR = 7;
  public static final int AND = 34;
  public static final int IGUAL = 20;
  public static final int CARACTER = 36;
  public static final int OR = 35;
  public static final int PREGUNTA = 32;
  public static final int IF = 4;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int PARIZQ = 14;
  public static final int RETURN = 37;
  public static final int AMP = 31;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 33;
  public static final int MENOS = 24;
  public static final int MENOR = 19;
  public static final int VOID = 30;
  public static final int PRINTF = 28;
  public static final int MAYOR = 18;
  public static final int ELSE = 5;
  public static final int IGUALIGUAL = 21;
  public static final int WHILE = 6;
  public static final int LLAVEIZQ = 16;
  public static final int PARDER = 15;
  public static final int DIVISION = 26;
  public static final int MAS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NUMEROS",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "INTEGER",
  "CHAR",
  "ASTERISCO",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "COMA",
  "PARIZQ",
  "PARDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "IGUALIGUAL",
  "MAS",
  "MASMAS",
  "MENOS",
  "MENOSMENOS",
  "DIVISION",
  "DIFERENTE",
  "PRINTF",
  "SCANF",
  "VOID",
  "AMP",
  "PREGUNTA",
  "CADENA",
  "AND",
  "OR",
  "CARACTER",
  "RETURN",
  "COMILLADOBLE"
  };
}

